### PR TITLE
devel/sip: Update to 5.4.0

### PR DESCRIPTION
**Pull request by lbartoletti**
Hello,

This is the WIP branch of sip update to 5.x (and maybe 6.x later, don't know yet...) with Qt and PyQt 5.15.1.

cc @madpilot78 for calibre
and @rhurlin for qgis

TODO list (AFAIK):

- [X] graphics/qgis, graphics/qgis-ltr
- [X] deskutils/calibre
- [X] net/libarcus
- [X] devel/libsavitar
- [x] science/scidavis (python options is unset)
- [x] science/py-veusz
- [x] graphics/py-python-poppler-qt5

### CODE REVIEW

**Comment by lbartoletti** [comment]
FYI, PYQT_SIPDIR will not be `/usr/local/share/PyQt5/${PYTHON_VER}/sip/`but `/usr/local/lib/python${PYTHON_VER}/site-packages/PyQt5/bindings`

**Comment by lbartoletti** [comment]
some ports, like calibre, will require `py-qtbuilder`

**Comment by lbartoletti** [comment]
@madpilot78 calibre is sip5 ready.
It builds (poudriere), I let you test it and make fixes if needed on this update; I focused on compiling with sip5.

**Comment by madpilot78** [comment]
@lbartoletti Thanks for your work. I'll try to test these changes in the next few days and report back.

**Comment by madpilot78** [comment]
@lbartoletti I have compiled and installed calibre 5.2.0 using the updates in this PR and it seems to work fine on my machine. Also the rest of qt5 seems to work fine.

**Pull request closed without merging**
